name: Build Chain

on: [pull_request]

jobs:
  build-chain-openjdk8:
    runs-on: ubuntu-latest
    name: Pull Request openjdk8
    steps:
    - uses: actions/checkout@v2
    - name: Build Chain
      id: build-chain
      uses: kiegroup/github-action-build-chain@openjdk8
      with:
        parent-dependencies: 'kie-wb-playground'
        child-dependencies: 'drools-wb'
        build-command: 'mvn -e -nsu -Dfull clean install -Prun-code-coverage -Pwildfly -Dcontainer=wildfly -Dcontainer.profile=wildfly -Dintegration-tests=true -Dmaven.test.failure.ignore=true -Dwebdriver.firefox.bin=/opt/tools/firefox-60esr/firefox-bin -DjvmArgs="-Xms1g -Xmx5g"'
        build-command-upstream: "mvn -e -T1C clean install -DskipTests -Dgwt.compiler.skip=true -Dgwt.skipCompilation=true -Denforcer.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true"
        workflow-file-name: "pull_request.yml"
      env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  build-chain-openjdk11:
    runs-on: ubuntu-latest
    name: Pull Request openjdk11
    steps:
    - uses: actions/checkout@v2
    - name: Build Chain
      id: build-chain
      uses: kiegroup/github-action-build-chain@openjdk11
      with:
        parent-dependencies: 'kie-wb-playground'
        child-dependencies: 'drools-wb'
        build-command: 'mvn -e -nsu -Dfull clean install -Prun-code-coverage -Pwildfly -Dcontainer=wildfly -Dcontainer.profile=wildfly -Dintegration-tests=true -Dmaven.test.failure.ignore=true -Dwebdriver.firefox.bin=/opt/tools/firefox-60esr/firefox-bin -DjvmArgs="-Xms1g -Xmx5g"'
        build-command-upstream: "mvn -e -T1C clean install -DskipTests -Dgwt.compiler.skip=true -Dgwt.skipCompilation=true -Denforcer.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true"
        workflow-file-name: "pull_request.yml"
      env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
